Initial ocfp kit feature from pairing with Pururva. (#30)
[Improvements]

* Added `ocfp` feature which encodes the opensource cloud foundry platform reference architecture. `ocfp` specifies that **inputs for features come from vault**.

  The reference architecture specifies the `network`, `vm_type`, `disk_type`, and `azs` based on `dev` vs `prod` environment scales.

  Naming scheme is entirely based on environment name, and is designed to work with the `ocfp-ops-scripts` `ocfp` cli in order to generate configs, initialize and test environments.

---

Co-authored-by: Pururva Lakkad <pururval@buffalo.edu>
Co-authored-by: Dennis Bell <dennis.j.bell@gmail.com>

diff --git a/hooks/blueprint b/hooks/blueprint
--- a/hooks/blueprint
+++ b/hooks/blueprint
@@ -1,25 +1,60 @@
 #!/bin/bash
+
 set -eu
 
-declare -a merge
+declare -a merge opsfiles
+opsfiles=()
+ops_var='merge'
+want_feature "ocfp" && ops_var="opsfiles"
 
-validate_features oauth oauth-provider \
-                  proxy postgres-addon secure
+for want in ${GENESIS_REQUESTED_FEATURES}
+do
+  case ${want} in
+    (ocfp|oauth|oauth-provider|proxy|postgres-addon|secure|okta)
+      true
+      ;;
+    (*)
+      if [[ -f "$GENESIS_ROOT/ops/$want.yml" ]]
+      then eval "$ops_var+=( \"$GENESIS_ROOT/ops/$want.yml\" )"
+      else echo "ERROR: Unsupported feature: ${want}" ; exit 1
+      fi
+      ;;
+  esac
+done
 
-merge=( manifests/shield.yml manifests/releases/shield.yml )
+merge=( 
+  "manifests/shield.yml"
+  "manifests/releases/shield.yml"
+)
 
-want_feature oauth && merge+=( manifests/oauth.yml )
-want_feature postgres-addon && merge+=( manifests/addons/postgres.yml manifests/releases/shield-addon-postgres.yml )
-want_feature secure && merge+=( manifests/addons/secure.yml )
+want_feature postgres-addon && merge+=( 
+  "manifests/addons/postgres.yml"
+  "manifests/releases/shield-addon-postgres.yml"
+)
 
-if want_feature oauth-provider; then
+want_feature okta   && merge+=( "manifests/addons/okta.yml" )
+want_feature secure && merge+=( "manifests/addons/secure.yml" )
+want_feature oauth  && merge+=( "manifests/oauth.yml" )
+
+if want_feature oauth-provider
+then
   echo >&2 "The oauth-provider feature flag is now just called 'oauth'."
-  merge+=( manifests/oauth.yml )
+  merge+=( "manifests/oauth.yml" )
 fi
 
-if want_feature proxy; then
+if want_feature proxy
+then
   echo >&2 "You no longer need to explicitly specify the 'proxy' feature."
   echo >&2 "If you remove it, everything will still work as expected."
 fi
 
+# ocfp feature overide everything except opsfiles.
+want_feature ocfp && merge+=( 
+  "ocfp/meta.yml"
+  "ocfp/ocfp.yml"
+)
+
 echo "${merge[@]}"
+if (( ${#opsfiles[@]} > 0 ))
+then echo "${opsfiles[@]}"
+fi
