Genesis v2.7.6 updates
* Replaced params.env with genesis.env and params.bosh with
  genesis.bosh_env.

* Removed manual check for external domain from `check` hook, as genesis
  does this now.

* Replaced explicit 'secret/<vault-path>' with $GENESIS_SECRETS_BASE

* Improved output of addon and info

* Improved code as per shellcheck

diff --git a/hooks/check b/hooks/check
--- a/hooks/check
+++ b/hooks/check
@@ -2,38 +2,13 @@
 
 # Cloud Config checks
 if [[ -n "$GENESIS_CLOUD_CONFIG" ]] ; then
-  if ! want_feature proto; then
-    cloud_config_needs vm_type    $(lookup params.shield_vm_type    small)
-    cloud_config_needs disk_type  $(lookup params.shield_disk_pool  shield)
-    cloud_config_needs network    $(lookup params.shield_network    shield)
-    check_cloud_config && describe "  cloud-config [#G{OK}]"
-  fi
-fi
-
-# Environment Parameter checks
-ok=yes
-domain=$(lookup params.external_domain)
-if [[ -z "$domain" ]]; then domain="$(lookup params.shield_static_ip)"; fi
-describe "  checking if our certificates match the SHIELD external domain ($domain)..."
-vault="secret/$GENESIS_VAULT_PREFIX"
-for cert in certs/server; do
-  if ! safe exists "$vault/$cert"; then
-    describe "    - $vault/$cert [#Y{MISSING}]"
+  cloud_config_needs vm_type    "$(lookup params.shield_vm_type    small)"
+  cloud_config_needs disk_type  "$(lookup params.shield_disk_pool  shield)"
+  cloud_config_needs network    "$(lookup params.shield_network    shield)"
+  if check_cloud_config; then
+    describe "  cloud config [#G{OK}]"
   else
-    if safe --quiet x509 validate "$vault/$cert" --for "$domain" >/dev/null 2>&1; then
-      describe "    - $vault/$cert [#G{OK}]"
-    else
-      describe "    - $vault/$cert [#R{INVALID}]"
-      safe x509 validate "$vault/$cert" --for "$domain" 2>&1 | sed -e 's/^/      /';
-      ok=no
-      echo
-    fi
+    describe "  cloud config [#R{FAILED}]"
+    exit 1
   fi
-done
-
-if [[ "$ok" = "yes" ]]; then
-  describe "  environment files [#G{OK}]"
-else
-  describe "  environment files [#R{FAILED}]"
-  exit 1
 fi
